### PR TITLE
Merge branch 'master' of https://github.com/mempool/mempool

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by wiz** [comment]
@ripcurlx we’re going to drop bisq support from the mempool open source project, so now would be a good time to merge this PR since you’ll need to maintain the bisq fork of mempool from now on

**Comment by wiz** [comment]
@cbeams can you merge this? we are about to remove bisq support from mempool so this needs to be the fork point, see https://github.com/mempool/mempool/pull/4786

**Comment by cbeams** [comment]
Hey @wiz, thanks for the heads up. As for me merging this PR, I don't have rights and I'm not quite sure what the implications of doing so would be. I'll try to flesh that out below.

I see, per your comment at https://github.com/bisq-network/roles/issues/9#issuecomment-1958777648 that @emzy has agreed to take over the bisq.markets domain. @emzy is that right, and has this already been done?

Will that instance at bisq.markets need to be migrated elsewhere? And is the idea that it would be stood up against this repository at the "fork point" of this PR being merged?

As for actually merging the PR, @gabernard should be able to do it. @emzy, if you do indeed plan to take over the domain and run the instance at bisq.markets based on this fork, perhaps you could verify everything works as expected against this PR and raise any questions you have here if not?

Thanks, all. Perhaps with a few more comments here, we can get a plan together and then make this change step by step.

**Comment by Emzy** [comment]
I don't want to take over the domain.
I already run an instance at https://bisq.mempool.emzy.de/

**Comment by cbeams** [comment]
> I don't want to take over the domain. I already run an instance at https://bisq.mempool.emzy.de/

@Emzy would it be ok for you if we (a) 302 bisq.markets to bisq.mempool.emzy.de or (b) set up a reverse proxy to it as near-term solutions?

Also, @Emzy, would you be planning to run your instance off of this fork going forward?

@wiz, I'll get back here regarding the merge and will follow up with you regarding taking over the domain.

**Comment by Emzy** [comment]
I'm OK with the redirect and reverse proxy. 

Let me try set up a new server with this fork. I'm planing to upgrade the hardware anyway soon.

For now the old version is still running on bisq.mempool.emzy.de

**Comment by wiz** [comment]
Okay I think we've given more than fair warning - if you don't want to merge this PR then Bisq will be on its own.
Best of luck!

**Pull request closed without merging**
